name: ungrep-multiple-values
description: Ungrep multiple strings.
author: trickest
author_info: https://trickest.com
script: cat in/*/* | egrep -wv 'url|robots|linkfinder' | awk -F" " '{print $NF}' |
  tee out/output.txt
language: bash
